name: Publish Storybook
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  publish:
    name: Publish Storybook to GitHub Pages
    runs-on: ubuntu-latest
    outputs:
      folder_name: ${{ steps.publish.outputs.folder_name }}
      stories: ${{ steps.filter.outputs.stories }}
    steps:
      - name: Checkout 🛒
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            stories:
              - 'stories/**'
      - name: Install 🔧
        if: steps.filter.outputs.stories == 'true'
        run: |
          npm install
      - name: Publish Storybook 🚀
        id: publish
        if: steps.filter.outputs.stories == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x -o pipefail

          git config user.name "@linda-lai"
          git config user.email "29894441+linda-lai@users.noreply.github.com"

          BRANCH_NAME=$GITHUB_HEAD_REF
          if [ $GITHUB_REF == "refs/heads/main" ]
          then
              BRANCH_NAME="main"
          fi

          FOLDER_NAME="$(echo "docs-$BRANCH_NAME" | sed -e 's/refs\///g' | sed -e 's/[\/\\]/-/g')"

          npm run build-storybook

          git reset
          git fetch origin gh-pages

          git checkout gh-pages -f
          rm -rf $FOLDER_NAME
          mv storybook-static $FOLDER_NAME

          git add $FOLDER_NAME
          git commit $FOLDER_NAME -m "docs: Publish Storybook changes on $BRANCH_NAME to GitHub Pages [skip ci]" --allow-empty

          git push
          echo "Added/updated folder $FOLDER_NAME to gh-pages"
          echo "::set-output name=folder_name::$(echo $FOLDER_NAME)"
  comment:
    name: Add Storybook link as pull request comment
    runs-on: ubuntu-latest
    needs: publish
    if: github.event_name == 'pull_request'
    outputs:
      stories: ${{ steps.filter.outputs.stories }}
    env:
      STORYBOOK_URL: "https://linda-lai.github.io/storybook-github-pages-actions"
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            stories:
              - 'stories/**'
      - name: Add pull request comment
        uses: actions/github-script@v1
        if: steps.filter.outputs.stories == 'true'
        env:
          FOLDER_NAME: "${{ needs.publish.outputs.folder_name }}"
          STORYBOOK_URL: "${{ env.STORYBOOK_URL }}"
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { STORYBOOK_URL, FOLDER_NAME } = process.env
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Storybook was pre-published on Github Pages. See it on ${STORYBOOK_URL}/${FOLDER_NAME}/index.html`
            });
